### ISSUE TITLE
Sometimes, many modules are missing.

### ISSUE THREAD

**Issue by garronej** [yoshixmk/deno-x-ranking#4]
Hi, nice project!

As you can see on this screenshot, typescript, lodash and many more modules are missing.
![image](https://user-images.githubusercontent.com/6702424/87795411-49d33380-c848-11ea-82d2-32c075c57d46.png)

They appeared after reloading the page... no idea how to reproduce though.

:octocat:

**Comment by yoshixmk** [comment]
@garronej Thank you for reporting.  I know that when GithubAction is up and running, I can't get the display because of static content.  However, this is the first time that I can get a part of the display.  Do you know if it overlaps with the time when you confirmed the ranking?
https://github.com/yoshixmk/deno-x-ranking/actions

**Comment by garronej** [comment]
I can't say for sure but there is great chances I did the GET request while your gh Action workflow was running!

**Comment by yoshixmk** [comment]
@garronej It was supposed that Github Action would work at every 6 hours of cron job and push to main branch, and it would be possible to cover almost nothing like this. However, the cron job setting every 6 hours is actually being executed a number of times that you do not expect, so I contact support this.  
Also, as long as I use Github Page, I tolerate that may not be able to display correctly at the time of Deploy, so this issue will be closed.  

Please contact me if something happens again. Thank you

**Comment by garronej** [comment]
cool insight 
Gh Actions is still new, I experienced a number of glitch myself.

Thanks, bye
